<?php

echo '
           <!-- Google Code for
           &#1059;&#1089;&#1087;&#1077;&#1096;&#1085;&#1072;&#1103;
           &#1086;&#1087;&#1077;&#1088;&#1072;&#1094;&#1080;&#1103; Conversion

           Page -->
           <script type="text/javascript">
           /* <![CDATA[ */
           var google_conversion_id = 1004403209;
           var google_conversion_language = "en";
           var google_conversion_format = "3";
           var google_conversion_color = "ffffff";
           var google_conversion_label = "R7y_CJfwhAMQifT33gM";
           var google_conversion_value = 0;
           /* ]]> */
           </script>
           <script type="text/javascript"

           src="http://www.googleadservices.com/pagead/conversion.js">
           </script>
           <noscript>
           <div style="display:inline;">
           <img height="1" width="1" style="border-style:none;" alt=""

           src="http://www.googleadservices.com/pagead/conversion/1004403209/?

           label=R7y_CJfwhAMQifT33gM&amp;guid=ON&amp;script=0"/>
           </div>
           </noscript>
';

?>